sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: Guojinglei012615
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5tAdGhKMo3ovXBjoAon4
    access-key-secret: 1lH1Kn4iuGAiMnq5zG8716izewDXCf
    bucket-name: sky-qm
  redis:
    host: localhost
    port: 6379
    # password: Guojinglei012615
    database: 0
  wechat:
    appid: wx4043ca8c362ff62d
    secret: 4d0190f223c7b690a52a20c15a56960e
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: D:\apiclient_key.pem
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: D:\wechatpay_166D96F876F45C7D07CE98952A96EC980368ACFC.pem
    notifyUrl: https://10caac42.r26.cpolar.top/notify/paySuccess
    refundNotifyUrl: https://10caac42.r26.cpolar.top/notify/refundSuccess